upgraded to use argbash for parameter parsing. way better

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,33 +1,151 @@
 #!/bin/bash
+# version="0.1"
+#
+# This is an optional arguments-only example of Argbash potential
+#
+# ARG_OPTIONAL_SINGLE([image-name],[i],[name of the docker image to be pushed],[koehn/diaspora])
+# ARG_OPTIONAL_SINGLE([git-url],[g],[git URL from which to clone the code])
+# ARG_OPTIONAL_SINGLE([diaspora-version],[d],[version of the diaspora code to compile])
+# ARG_OPTIONAL_SINGLE([ruby-version],[r],[version of ruby to use])
+# ARG_OPTIONAL_SINGLE([gem-version],[G],[version of gem to use])
+# ARG_HELP([builds a Docker image of a Diaspora repository and pushes that image to Docker])
+# ARGBASH_GO()
+# needed because of Argbash --> m4_ignore([
+### START OF CODE GENERATED BY Argbash v2.5.1 one line above ###
+# Argbash is a bash code generator used to get arguments parsing right.
+# Argbash is FREE SOFTWARE, see https://argbash.io for more info
+# Generated online by https://argbash.io/generate
 
-function usage {
-  echo 'build [--image-name name] [--git-url url] [--diaspora-version version] [--ruby-version version] [--gem-version version]' >&2
+die()
+{
+	local _ret=$2
+	test -n "$_ret" || _ret=1
+	test "$_PRINT_HELP" = yes && print_help >&2
+	echo "$1" >&2
+	exit ${_ret}
 }
 
-IMAGE_NAME=koehn/diaspora
+begins_with_short_option()
+{
+	local first_option all_short_options
+	all_short_options='igdrGh'
+	first_option="${1:0:1}"
+	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
+}
 
-# NOTE: The BSD version of `getopt` is incompatible with the one this version expects.
-# On MacOS systems, install and use `gnu-getopt`. You have been warned. 
-OPTS=$(getopt -l "image-name:,git-url:,diaspora-version:,ruby-version:,gem-version:" -n 'build' -- "$@") ; err=$?
 
-if [ $err -ne 0 ] ; then usage ; exit 1; fi
 
-set -e
+# THE DEFAULTS INITIALIZATION - OPTIONALS
+_arg_image_name="koehn/diaspora"
+_arg_git_url=
+_arg_diaspora_version=
+_arg_ruby_version=
+_arg_gem_version=
 
-eval set -- "$OPTS"
+print_help ()
+{
+	printf "%s\n" "builds a Docker image of a Diaspora repository and pushes that image to Docker"
+	printf 'Usage: %s [-i|--image-name <arg>] [-g|--git-url <arg>] [-d|--diaspora-version <arg>] [-r|--ruby-version <arg>] [-G|--gem-version <arg>] [-h|--help]\n' "$0"
+	printf "\t%s\n" "-i,--image-name: name of the docker image to be pushed (default: '"koehn/diaspora"')"
+	printf "\t%s\n" "-g,--git-url: git URL from which to clone the code (no default)"
+	printf "\t%s\n" "-d,--diaspora-version: version of the diaspora code to compile (no default)"
+	printf "\t%s\n" "-r,--ruby-version: version of ruby to use (no default)"
+	printf "\t%s\n" "-G,--gem-version: version of gem to use (no default)"
+	printf "\t%s\n" "-h,--help: Prints help"
+}
+
+parse_commandline ()
+{
+	while test $# -gt 0
+	do
+		_key="$1"
+		case "$_key" in
+			-i|--image-name)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_arg_image_name="$2"
+				shift
+				;;
+			--image-name=*)
+				_arg_image_name="${_key##--image-name=}"
+				;;
+			-i*)
+				_arg_image_name="${_key##-i}"
+				;;
+			-g|--git-url)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_arg_git_url="$2"
+				shift
+				;;
+			--git-url=*)
+				_arg_git_url="${_key##--git-url=}"
+				;;
+			-g*)
+				_arg_git_url="${_key##-g}"
+				;;
+			-d|--diaspora-version)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_arg_diaspora_version="$2"
+				shift
+				;;
+			--diaspora-version=*)
+				_arg_diaspora_version="${_key##--diaspora-version=}"
+				;;
+			-d*)
+				_arg_diaspora_version="${_key##-d}"
+				;;
+			-r|--ruby-version)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_arg_ruby_version="$2"
+				shift
+				;;
+			--ruby-version=*)
+				_arg_ruby_version="${_key##--ruby-version=}"
+				;;
+			-r*)
+				_arg_ruby_version="${_key##-r}"
+				;;
+			-G|--gem-version)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_arg_gem_version="$2"
+				shift
+				;;
+			--gem-version=*)
+				_arg_gem_version="${_key##--gem-version=}"
+				;;
+			-G*)
+				_arg_gem_version="${_key##-G}"
+				;;
+			-h|--help)
+				print_help
+				exit 0
+				;;
+			-h*)
+				print_help
+				exit 0
+				;;
+			*)
+				_PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
+				;;
+		esac
+		shift
+	done
+}
+
+parse_commandline "$@"
+
+# OTHER STUFF GENERATED BY Argbash
+
+### END OF CODE GENERATED BY Argbash (sortof) ### ])
+# [ <-- needed because of Argbash
+
 
 DOCKER_TAG=latest
+IMAGE_NAME=$_arg_image_name
 
-while true; do
-  case "$1" in
-    --git-url ) BUILD_ARGS="$BUILD_ARGS --build-arg GIT_URL=$2 "; shift 2 ;;
-    --diaspora-version ) DOCKER_TAG=$2 ; BUILD_ARGS="$BUILD_ARGS --build-arg GIT_BRANCH=v$2 "; shift 2 ;;
-    --ruby-version ) BUILD_ARGS="$BUILD_ARGS --build-arg RUBY_VERSION=$2 "; shift 2 ;;
-    --gem-version ) BUILD_ARGS="$BUILD_ARGS --build-arg GEM_VERSION=$2 "; shift 2 ;;
-    --image-name ) IMAGE_NAME=$2 ; shift 2 ;;
-    * ) usage ; exit 1 ;;
-  esac
-done
+if [ -z "$_arg_git_url" ] ; then BUILD_ARGS="$BUILD_ARGS --build-arg GIT_URL=$_arg_git_url" ; fi
+if [ -z "$_arg_diaspora-version" ] ; then DOCKER_TAG=$diaspora_version ; BUILD_ARGS="$BUILD_ARGS --build-arg GIT_BRANCH=v$_arg_diaspora_version" ; fi
+if [ -z "$_arg_ruby_version" ] ; then BUILD_ARGS="$BUILD_ARGS --build-arg RUBY_VERSION=$_arg_ruby_version" ; fi
+if [ -z "$_arg_gem_version" ] ; then BUILD_ARGS="$BUILD_ARGS --build-arg GEM_VERSION=$_arg_gem_version" ; fi
 
 BUILD_ARGS="$BUILD_ARGS --build-arg DIASPORA_DOCKER_GIT_COMMIT=`git log -1 --format=%h` "
 
@@ -35,3 +153,4 @@ docker build -t $IMAGE_NAME:$DOCKER_TAG $BUILD_ARGS .
 
 docker push $IMAGE_NAME:$DOCKER_TAG
 
+# ] <-- needed because of Argbash
